---

# Declares conda channels and configures the basic runtime environment and shell.
# Many pipelines load 'base' first, followed by:
#     - program families specified by shared conda environments
#     - any dependencies/versions peculiar to the pipeline (which override the above)

channels:
    - conda-forge
    - bioconda
    - defaults

dependencies:
    - pigz=2.6 # parallel handling of gzip files
