
# functions for getting reference genome bases

#=====================================================================================
# load a genome index previously generated by samtools faidx
#-------------------------------------------------------------------------------------
loadFaidx <- function(dir){
    genome_file <- paste(env$GENOME, 'fa', sep = ".")
    genome_file <- paste(env$SHM_DIR_WRK, genome_file, sep = "/")
    genome_index_file <- paste(genome_file, 'fai', sep = ".")
    genome_con <<- file(genome_file, open = "rb")
    genome_index <<- read.table(genome_index_file, header = FALSE, sep = "\t", stringsAsFactors = FALSE)
    names(genome_index) <<- c('chrom', 'length', 'offset', 'lineSeqLen', 'lineLen')
}
#=====================================================================================

#=====================================================================================
# get a specified chunk of a single chromosome and rc if requested
#-------------------------------------------------------------------------------------
getRefSeq <- function(chrom, range, rc = FALSE) {
    index <- genome_index[genome_index$chrom == chrom, , drop = FALSE]    
    if(range[1] > range[2]) range <- rev(range)
    if(range[1] < 1) range[1] <- 1
    if(range[2] > index$length) range[2] <- index$length
    range[1] <- range[1] - 1
    range[2] <- range[2] - 1
    linesBeforePos1 <- floor(range[1] / index$lineSeqLen)  
    linesBeforePos2 <- floor(range[2] / index$lineSeqLen)
    seek(genome_con, where = index$offset + range[1] + linesBeforePos1, origin = "start", rw = "r") # accounts for newlines # nolint
    seq <- readChar(genome_con, diff(range) + 1 + (linesBeforePos2 - linesBeforePos1))
    seq <- toupper(gsub("[[:space:]]", "", seq))
    if(rc) seq <- rc(seq)
    seq
}
getRefSeq_padded <- function(chrom, pos, padding, rc = FALSE){
    getRefSeq(chrom, c(pos - padding, pos + padding), rc) # pos is central of odd-length string
}
#=====================================================================================
